//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: external.proto

package com.undercurrent.legacy.types.protos;

@kotlin.jvm.JvmName("-initializetxOutConfirmationNumber")
inline fun txOutConfirmationNumber(block: TxOutConfirmationNumberKt.Dsl.() -> kotlin.Unit): com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber =
  TxOutConfirmationNumberKt.Dsl._create(com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber.newBuilder())
    .apply { block() }._build()
object TxOutConfirmationNumberKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber.Builder): Dsl =
        Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber =
      _builder.build()

    /**
     * <code>bytes hash = 1;</code>
     */
    var hash: com.google.protobuf.ByteString
      @JvmName("getHash")
      get() = _builder.getHash()
      @JvmName("setHash")
      set(value) {
        _builder.setHash(value)
      }
    /**
     * <code>bytes hash = 1;</code>
     */
    fun clearHash() {
      _builder.clearHash()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber.copy(block: TxOutConfirmationNumberKt.Dsl.() -> kotlin.Unit): com.undercurrent.legacy.types.protos.MobileCoinAPI.TxOutConfirmationNumber =
   TxOutConfirmationNumberKt.Dsl._create(this.toBuilder()).apply { block() }._build()

